window.HIPPOCRATES_DATA = {
  "summary": [
    {
      "doctor_id": "D01",
      "doctor_practice_type": "rural",
      "patients": 231,
      "deaths": 13,
      "mortality_rate": 0.056277
    },
    {
      "doctor_id": "D02",
      "doctor_practice_type": "urban",
      "patients": 258,
      "deaths": 17,
      "mortality_rate": 0.065891
    },
    {
      "doctor_id": "D03",
      "doctor_practice_type": "urban",
      "patients": 214,
      "deaths": 16,
      "mortality_rate": 0.074766
    },
    {
      "doctor_id": "D04",
      "doctor_practice_type": "urban",
      "patients": 255,
      "deaths": 14,
      "mortality_rate": 0.054902
    },
    {
      "doctor_id": "D05",
      "doctor_practice_type": "suburban",
      "patients": 240,
      "deaths": 17,
      "mortality_rate": 0.070833
    },
    {
      "doctor_id": "D06",
      "doctor_practice_type": "suburban",
      "patients": 196,
      "deaths": 11,
      "mortality_rate": 0.056122
    },
    {
      "doctor_id": "D07",
      "doctor_practice_type": "urban",
      "patients": 190,
      "deaths": 7,
      "mortality_rate": 0.036842
    },
    {
      "doctor_id": "D08",
      "doctor_practice_type": "urban",
      "patients": 214,
      "deaths": 14,
      "mortality_rate": 0.065421
    },
    {
      "doctor_id": "D09",
      "doctor_practice_type": "rural",
      "patients": 249,
      "deaths": 13,
      "mortality_rate": 0.052209
    },
    {
      "doctor_id": "D10",
      "doctor_practice_type": "urban",
      "patients": 215,
      "deaths": 18,
      "mortality_rate": 0.083721
    },
    {
      "doctor_id": "D11",
      "doctor_practice_type": "suburban",
      "patients": 186,
      "deaths": 8,
      "mortality_rate": 0.043011
    },
    {
      "doctor_id": "D12",
      "doctor_practice_type": "urban",
      "patients": 228,
      "deaths": 9,
      "mortality_rate": 0.039474
    },
    {
      "doctor_id": "D13",
      "doctor_practice_type": "urban",
      "patients": 225,
      "deaths": 20,
      "mortality_rate": 0.088889
    },
    {
      "doctor_id": "D14",
      "doctor_practice_type": "urban",
      "patients": 232,
      "deaths": 11,
      "mortality_rate": 0.047414
    },
    {
      "doctor_id": "D15",
      "doctor_practice_type": "rural",
      "patients": 215,
      "deaths": 8,
      "mortality_rate": 0.037209
    },
    {
      "doctor_id": "D16",
      "doctor_practice_type": "urban",
      "patients": 229,
      "deaths": 13,
      "mortality_rate": 0.056769
    },
    {
      "doctor_id": "D17",
      "doctor_practice_type": "suburban",
      "patients": 188,
      "deaths": 11,
      "mortality_rate": 0.058511
    },
    {
      "doctor_id": "D18",
      "doctor_practice_type": "suburban",
      "patients": 249,
      "deaths": 19,
      "mortality_rate": 0.076305
    },
    {
      "doctor_id": "D19",
      "doctor_practice_type": "suburban",
      "patients": 195,
      "deaths": 8,
      "mortality_rate": 0.041026
    },
    {
      "doctor_id": "D20",
      "doctor_practice_type": "rural",
      "patients": 197,
      "deaths": 9,
      "mortality_rate": 0.045685
    }
  ],
  "deaths": [
    {
      "patient_id": "P00017",
      "doctor_id": "D01",
      "patient_age": 85,
      "patient_sex": "M",
      "date_of_death": "2022-08-19",
      "hour_of_death": 17,
      "home_visit_same_day": 0,
      "place_of_death": "home",
      "cause_category": "respiratory",
      "doctor_practice_type": "rural"
    },
    {
      "patient_id": "P00020",
      "doctor_id": "D01",
      "patient_age": 74,
      "patient_sex": "M",
      "date_of_death": "2022-07-26",
      "hour_of_death": 1,
      "home_visit_same_day": 0,
      "place_of_death": "home",
      "cause_category": "cardiovascular",
      "doctor_practice_type": "rural"
    },
    {
      "patient_id": "P00031",
      "doctor_id": "D01",
      "patient_age": 75,
      "patient_sex": "F",
      "date_of_death": "2022-08-13",
      "hour_of_death": 0,
      "home_visit_same_day": 0,
      "place_of_death": "hospital",
      "cause_category": "cancer",
      "doctor_practice_type": "rural"
    },
    {
      "patient_id": "P00057",
      "doctor_id": "D01",
      "patient_age": 92,
      "patient_sex": "F",
      "date_of_death": "2022-02-05",
      "hour_of_death": 4,
      "home_visit_same_day": 0,
      "place_of_death": "hospital",
      "cause_category": "frailty",
      "doctor_practice_type": "rural"
    },
    {
      "patient_id": "P00060",
      "doctor_id": "D01",
      "patient_age": 81,
      "patient_sex": "F",
      "date_of_death": "2022-02-23",
      "hour_of_death": 2,
      "home_visit_same_day": 0,
      "place_of_death": "care_home",
      "cause_category": "respiratory",
      "doctor_practice_type": "rural"
    },
    {
      "patient_id": "P00066",
      "doctor_id": "D01",
      "patient_age": 80,
      "patient_sex": "M",
      "date_of_death": "2022-06-03",
      "hour_of_death": 16,
      "home_visit_same_day": 0,
      "place_of_death": "home",
      "cause_category": "cardiovascular",
      "doctor_practice_type": "rural"
    },
    {
      "patient_id": "P00069",
      "doctor_id": "D01",
      "patient_age": 91,
      "patient_sex": "M",
      "date_of_death": "2022-08-11",
      "hour_of_death": 23,
      "home_visit_same_day": 1,
      "place_of_death": "hospital",
      "cause_category": "cancer",
      "doctor_practice_type": "rural"
    },
    {
      "patient_id": "P00073",
      "doctor_id": "D01",
      "patient_age": 85,
      "patient_sex": "F",
      "date_of_death": "2022-02-04",
      "hour_of_death": 5,
      "home_visit_same_day": 0,
      "place_of_death": "hospital",
      "cause_category": "frailty",
      "doctor_practice_type": "rural"
    },
    {
      "patient_id": "P00106",
      "doctor_id": "D01",
      "patient_age": 86,
      "patient_sex": "F",
      "date_of_death": "2022-04-15",
      "hour_of_death": 4,
      "home_visit_same_day": 0,
      "place_of_death": "care_home",
      "cause_category": "other",
      "doctor_practice_type": "rural"
    },
    {
      "patient_id": "P00169",
      "doctor_id": "D01",
      "patient_age": 80,
      "patient_sex": "F",
      "date_of_death": "2023-07-29",
      "hour_of_death": 15,
      "home_visit_same_day": 0,
      "place_of_death": "care_home",
      "cause_category": "respiratory",
      "doctor_practice_type": "rural"
    },
    {
      "patient_id": "P00170",
      "doctor_id": "D01",
      "patient_age": 83,
      "patient_sex": "F",
      "date_of_death": "2022-06-28",
      "hour_of_death": 14,
      "home_visit_same_day": 0,
      "place_of_death": "home",
      "cause_category": "cardiovascular",
      "doctor_practice_type": "rural"
    },
    {
      "patient_id": "P00209",
      "doctor_id": "D01",
      "patient_age": 81,
      "patient_sex": "M",
      "date_of_death": "2023-06-22",
      "hour_of_death": 14,
      "home_visit_same_day": 1,
      "place_of_death": "care_home",
      "cause_category": "cardiovascular",
      "doctor_practice_type": "rural"
    },
    {
      "patient_id": "P00230",
      "doctor_id": "D01",
      "patient_age": 98,
      "patient_sex": "F",
      "date_of_death": "2023-09-09",
      "hour_of_death": 2,
      "home_visit_same_day": 0,
      "place_of_death": "care_home",
      "cause_category": "cardiovascular",
      "doctor_practice_type": "rural"
    },
    {
      "patient_id": "P00237",
      "doctor_id": "D02",
      "patient_age": 79,
      "patient_sex": "M",
      "date_of_death": "2023-11-03",
      "hour_of_death": 10,
      "home_visit_same_day": 0,
      "place_of_death": "home",
      "cause_category": "frailty",
      "doctor_practice_type": "urban"
    },
    {
      "patient_id": "P00245",
      "doctor_id": "D02",
      "patient_age": 68,
      "patient_sex": "M",
      "date_of_death": "2022-02-02",
      "hour_of_death": 13,
      "home_visit_same_day": 0,
      "place_of_death": "hospital",
      "cause_category": "cardiovascular",
      "doctor_practice_type": "urban"
    },
    {
      "patient_id": "P00258",
      "doctor_id": "D02",
      "patient_age": 66,
      "patient_sex": "M",
      "date_of_death": "2022-10-01",
      "hour_of_death": 0,
      "home_visit_same_day": 0,
      "place_of_death": "care_home",
      "cause_category": "frailty",
      "doctor_practice_type": "urban"
    },
    {
      "patient_id": "P00262",
      "doctor_id": "D02",
      "patient_age": 85,
      "patient_sex": "M",
      "date_of_death": "2022-08-13",
      "hour_of_death": 6,
      "home_visit_same_day": 1,
      "place_of_death": "hospital",
      "cause_category": "frailty",
      "doctor_practice_type": "urban"
    },
    {
      "patient_id": "P00286",
      "doctor_id": "D02",
      "patient_age": 86,
      "patient_sex": "F",
      "date_of_death": "2023-05-26",
      "hour_of_death": 8,
      "home_visit_same_day": 1,
      "place_of_death": "hospital",
      "cause_category": "cardiovascular",
      "doctor_practice_type": "urban"
    },
    {
      "patient_id": "P00330",
      "doctor_id": "D02",
      "patient_age": 86,
      "patient_sex": "M",
      "date_of_death": "2022-06-09",
      "hour_of_death": 19,
      "home_visit_same_day": 0,
      "place_of_death": "home",
      "cause_category": "respiratory",
      "doctor_practice_type": "urban"
    },
    {
      "patient_id": "P00338",
      "doctor_id": "D02",
      "patient_age": 70,
      "patient_sex": "M",
      "date_of_death": "2023-04-26",
      "hour_of_death": 14,
      "home_visit_same_day": 1,
      "place_of_death": "hospital",
      "cause_category": "respiratory",
      "doctor_practice_type": "urban"
    },
    {
      "patient_id": "P00370",
      "doctor_id": "D02",
      "patient_age": 73,
      "patient_sex": "F",
      "date_of_death": "2022-03-28",
      "hour_of_death": 0,
      "home_visit_same_day": 0,
      "place_of_death": "hospital",
      "cause_category": "frailty",
      "doctor_practice_type": "urban"
    },
    {
      "patient_id": "P00372",
      "doctor_id": "D02",
      "patient_age": 69,
      "patient_sex": "M",
      "date_of_death": "2023-01-03",
      "hour_of_death": 7,
      "home_visit_same_day": 0,
      "place_of_death": "care_home",
      "cause_category": "cancer",
      "doctor_practice_type": "urban"
    },
    {
      "patient_id": "P00374",
      "doctor_id": "D02",
      "patient_age": 80,
      "patient_sex": "F",
      "date_of_death": "2023-01-05",
      "hour_of_death": 0,
      "home_visit_same_day": 0,
      "place_of_death": "hospital",
      "cause_category": "other",
      "doctor_practice_type": "urban"
    },
    {
      "patient_id": "P00375",
      "doctor_id": "D02",
      "patient_age": 73,
      "patient_sex": "F",
      "date_of_death": "2022-09-30",
      "hour_of_death": 5,
      "home_visit_same_day": 0,
      "place_of_death": "hospital",
      "cause_category": "respiratory",
      "doctor_practice_type": "urban"
    },
    {
      "patient_id": "P00389",
      "doctor_id": "D02",
      "patient_age": 85,
      "patient_sex": "M",
      "date_of_death": "2023-08-25",
      "hour_of_death": 20,
      "home_visit_same_day": 0,
      "place_of_death": "care_home",
      "cause_category": "frailty",
      "doctor_practice_type": "urban"
    },
    {
      "patient_id": "P00405",
      "doctor_id": "D02",
      "patient_age": 72,
      "patient_sex": "M",
      "date_of_death": "2022-07-01",
      "hour_of_death": 11,
      "home_visit_same_day": 1,
      "place_of_death": "hospital",
      "cause_category": "other",
      "doctor_practice_type": "urban"
    },
    {
      "patient_id": "P00444",
      "doctor_id": "D02",
      "patient_age": 68,
      "patient_sex": "F",
      "date_of_death": "2022-02-16",
      "hour_of_death": 13,
      "home_visit_same_day": 1,
      "place_of_death": "home",
      "cause_category": "cancer",
      "doctor_practice_type": "urban"
    },
    {
      "patient_id": "P00458",
      "doctor_id": "D02",
      "patient_age": 82,
      "patient_sex": "M",
      "date_of_death": "2022-02-04",
      "hour_of_death": 15,
      "home_visit_same_day": 0,
      "place_of_death": "hospital",
      "cause_category": "cancer",
      "doctor_practice_type": "urban"
    },
    {
      "patient_id": "P00466",
      "doctor_id": "D02",
      "patient_age": 82,
      "patient_sex": "F",
      "date_of_death": "2022-09-19",
      "hour_of_death": 9,
      "home_visit_same_day": 1,
      "place_of_death": "home",
      "cause_category": "cancer",
      "doctor_practice_type": "urban"
    },
    {
      "patient_id": "P00467",
      "doctor_id": "D02",
      "patient_age": 53,
      "patient_sex": "F",
      "date_of_death": "2022-10-29",
      "hour_of_death": 4,
      "home_visit_same_day": 1,
      "place_of_death": "care_home",
      "cause_category": "cardiovascular",
      "doctor_practice_type": "urban"
    },
    {
      "patient_id": "P00512",
      "doctor_id": "D03",
      "patient_age": 84,
      "patient_sex": "M",
      "date_of_death": "2022-11-19",
      "hour_of_death": 13,
      "home_visit_same_day": 0,
      "place_of_death": "home",
      "cause_category": "cancer",
      "doctor_practice_type": "urban"
    },
    {
      "patient_id": "P00515",
      "doctor_id": "D03",
      "patient_age": 67,
      "patient_sex": "F",
      "date_of_death": "2022-03-06",
      "hour_of_death": 13,
      "home_visit_same_day": 0,
      "place_of_death": "home",
      "cause_category": "cardiovascular",
      "doctor_practice_type": "urban"
    },
    {
      "patient_id": "P00522",
      "doctor_id": "D03",
      "patient_age": 64,
      "patient_sex": "F",
      "date_of_death": "2022-08-19",
      "hour_of_death": 4,
      "home_visit_same_day": 0,
      "place_of_death": "hospital",
      "cause_category": "respiratory",
      "doctor_practice_type": "urban"
    },
    {
      "patient_id": "P00528",
      "doctor_id": "D03",
      "patient_age": 68,
      "patient_sex": "F",
      "date_of_death": "2022-06-03",
      "hour_of_death": 14,
      "home_visit_same_day": 0,
      "place_of_death": "care_home",
      "cause_category": "cancer",
      "doctor_practice_type": "urban"
    },
    {
      "patient_id": "P00544",
      "doctor_id": "D03",
      "patient_age": 77,
      "patient_sex": "M",
      "date_of_death": "2023-01-22",
      "hour_of_death": 10,
      "home_visit_same_day": 0,
      "place_of_death": "hospital",
      "cause_category": "other",
      "doctor_practice_type": "urban"
    },
    {
      "patient_id": "P00563",
      "doctor_id": "D03",
      "patient_age": 87,
      "patient_sex": "F",
      "date_of_death": "2022-06-10",
      "hour_of_death": 9,
      "home_visit_same_day": 1,
      "place_of_death": "hospital",
      "cause_category": "respiratory",
      "doctor_practice_type": "urban"
    },
    {
      "patient_id": "P00572",
      "doctor_id": "D03",
      "patient_age": 81,
      "patient_sex": "M",
      "date_of_death": "2022-06-19",
      "hour_of_death": 16,
      "home_visit_same_day": 0,
      "place_of_death": "hospital",
      "cause_category": "cardiovascular",
      "doctor_practice_type": "urban"
    },
    {
      "patient_id": "P00588",
      "doctor_id": "D03",
      "patient_age": 76,
      "patient_sex": "M",
      "date_of_death": "2022-09-11",
      "hour_of_death": 3,
      "home_visit_same_day": 0,
      "place_of_death": "hospital",
      "cause_category": "cardiovascular",
      "doctor_practice_type": "urban"
    },
    {
      "patient_id": "P00590",
      "doctor_id": "D03",
      "patient_age": 72,
      "patient_sex": "M",
      "date_of_death": "2022-02-07",
      "hour_of_death": 16,
      "home_visit_same_day": 0,
      "place_of_death": "hospital",
      "cause_category": "other",
      "doctor_practice_type": "urban"
    },
    {
      "patient_id": "P00599",
      "doctor_id": "D03",
      "patient_age": 74,
      "patient_sex": "M",
      "date_of_death": "2022-03-14",
      "hour_of_death": 4,
      "home_visit_same_day": 0,
      "place_of_death": "care_home",
      "cause_category": "frailty",
      "doctor_practice_type": "urban"
    },
    {
      "patient_id": "P00604",
      "doctor_id": "D03",
      "patient_age": 74,
      "patient_sex": "M",
      "date_of_death": "2022-07-12",
      "hour_of_death": 12,
      "home_visit_same_day": 0,
      "place_of_death": "care_home",
      "cause_category": "frailty",
      "doctor_practice_type": "urban"
    },
    {
      "patient_id": "P00622",
      "doctor_id": "D03",
      "patient_age": 93,
      "patient_sex": "M",
      "date_of_death": "2023-03-28",
      "hour_of_death": 5,
      "home_visit_same_day": 0,
      "place_of_death": "home",
      "cause_category": "other",
      "doctor_practice_type": "urban"
    },
    {
      "patient_id": "P00624",
      "doctor_id": "D03",
      "patient_age": 83,
      "patient_sex": "F",
      "date_of_death": "2022-03-09",
      "hour_of_death": 13,
      "home_visit_same_day": 0,
      "place_of_death": "care_home",
      "cause_category": "cardiovascular",
      "doctor_practice_type": "urban"
    },
    {
      "patient_id": "P00628",
      "doctor_id": "D03",
      "patient_age": 77,
      "patient_sex": "F",
      "date_of_death": "2023-03-12",
      "hour_of_death": 12,
      "home_visit_same_day": 1,
      "place_of_death": "home",
      "cause_category": "cardiovascular",
      "doctor_practice_type": "urban"
    },
    {
      "patient_id": "P00689",
      "doctor_id": "D03",
      "patient_age": 63,
      "patient_sex": "F",
      "date_of_death": "2023-07-29",
      "hour_of_death": 7,
      "home_visit_same_day": 0,
      "place_of_death": "care_home",
      "cause_category": "respiratory",
      "doctor_practice_type": "urban"
    },
    {
      "patient_id": "P00692",
      "doctor_id": "D03",
      "patient_age": 68,
      "patient_sex": "M",
      "date_of_death": "2023-11-06",
      "hour_of_death": 8,
      "home_visit_same_day": 0,
      "place_of_death": "home",
      "cause_category": "other",
      "doctor_practice_type": "urban"
    },
    {
      "patient_id": "P00720",
      "doctor_id": "D04",
      "patient_age": 61,
      "patient_sex": "F",
      "date_of_death": "2023-03-22",
      "hour_of_death": 4,
      "home_visit_same_day": 0,
      "place_of_death": "hospital",
      "cause_category": "cardiovascular",
      "doctor_practice_type": "urban"
    },
    {
      "patient_id": "P00735",
      "doctor_id": "D04",
      "patient_age": 91,
      "patient_sex": "M",
      "date_of_death": "2023-05-15",
      "hour_of_death": 10,
      "home_visit_same_day": 0,
      "place_of_death": "hospital",
      "cause_category": "respiratory",
      "doctor_practice_type": "urban"
    },
    {
      "patient_id": "P00736",
      "doctor_id": "D04",
      "patient_age": 68,
      "patient_sex": "M",
      "date_of_death": "2023-11-17",
      "hour_of_death": 19,
      "home_visit_same_day": 0,
      "place_of_death": "home",
      "cause_category": "frailty",
      "doctor_practice_type": "urban"
    },
    {
      "patient_id": "P00739",
      "doctor_id": "D04",
      "patient_age": 75,
      "patient_sex": "F",
      "date_of_death": "2023-04-12",
      "hour_of_death": 20,
      "home_visit_same_day": 0,
      "place_of_death": "hospital",
      "cause_category": "cancer",
      "doctor_practice_type": "urban"
    },
    {
      "patient_id": "P00778",
      "doctor_id": "D04",
      "patient_age": 70,
      "patient_sex": "F",
      "date_of_death": "2022-01-05",
      "hour_of_death": 8,
      "home_visit_same_day": 0,
      "place_of_death": "hospital",
      "cause_category": "other",
      "doctor_practice_type": "urban"
    },
    {
      "patient_id": "P00823",
      "doctor_id": "D04",
      "patient_age": 50,
      "patient_sex": "M",
      "date_of_death": "2022-04-17",
      "hour_of_death": 4,
      "home_visit_same_day": 0,
      "place_of_death": "home",
      "cause_category": "cancer",
      "doctor_practice_type": "urban"
    },
    {
      "patient_id": "P00834",
      "doctor_id": "D04",
      "patient_age": 72,
      "patient_sex": "F",
      "date_of_death": "2023-09-14",
      "hour_of_death": 13,
      "home_visit_same_day": 1,
      "place_of_death": "hospital",
      "cause_category": "cardiovascular",
      "doctor_practice_type": "urban"
    },
    {
      "patient_id": "P00860",
      "doctor_id": "D04",
      "patient_age": 67,
      "patient_sex": "F",
      "date_of_death": "2023-08-23",
      "hour_of_death": 17,
      "home_visit_same_day": 0,
      "place_of_death": "care_home",
      "cause_category": "respiratory",
      "doctor_practice_type": "urban"
    },
    {
      "patient_id": "P00866",
      "doctor_id": "D04",
      "patient_age": 67,
      "patient_sex": "M",
      "date_of_death": "2023-05-22",
      "hour_of_death": 2,
      "home_visit_same_day": 0,
      "place_of_death": "care_home",
      "cause_category": "other",
      "doctor_practice_type": "urban"
    },
    {
      "patient_id": "P00876",
      "doctor_id": "D04",
      "patient_age": 73,
      "patient_sex": "F",
      "date_of_death": "2023-08-21",
      "hour_of_death": 1,
      "home_visit_same_day": 0,
      "place_of_death": "care_home",
      "cause_category": "cardiovascular",
      "doctor_practice_type": "urban"
    },
    {
      "patient_id": "P00882",
      "doctor_id": "D04",
      "patient_age": 68,
      "patient_sex": "F",
      "date_of_death": "2022-05-24",
      "hour_of_death": 3,
      "home_visit_same_day": 0,
      "place_of_death": "hospital",
      "cause_category": "cardiovascular",
      "doctor_practice_type": "urban"
    },
    {
      "patient_id": "P00894",
      "doctor_id": "D04",
      "patient_age": 80,
      "patient_sex": "F",
      "date_of_death": "2022-07-09",
      "hour_of_death": 14,
      "home_visit_same_day": 0,
      "place_of_death": "home",
      "cause_category": "cardiovascular",
      "doctor_practice_type": "urban"
    },
    {
      "patient_id": "P00904",
      "doctor_id": "D04",
      "patient_age": 73,
      "patient_sex": "M",
      "date_of_death": "2023-02-14",
      "hour_of_death": 18,
      "home_visit_same_day": 0,
      "place_of_death": "hospital",
      "cause_category": "cancer",
      "doctor_practice_type": "urban"
    },
    {
      "patient_id": "P00924",
      "doctor_id": "D04",
      "patient_age": 73,
      "patient_sex": "M",
      "date_of_death": "2023-01-16",
      "hour_of_death": 10,
      "home_visit_same_day": 0,
      "place_of_death": "hospital",
      "cause_category": "frailty",
      "doctor_practice_type": "urban"
    },
    {
      "patient_id": "P00966",
      "doctor_id": "D05",
      "patient_age": 89,
      "patient_sex": "F",
      "date_of_death": "2023-08-05",
      "hour_of_death": 7,
      "home_visit_same_day": 1,
      "place_of_death": "hospital",
      "cause_category": "cardiovascular",
      "doctor_practice_type": "suburban"
    },
    {
      "patient_id": "P00968",
      "doctor_id": "D05",
      "patient_age": 85,
      "patient_sex": "M",
      "date_of_death": "2023-12-09",
      "hour_of_death": 14,
      "home_visit_same_day": 0,
      "place_of_death": "care_home",
      "cause_category": "frailty",
      "doctor_practice_type": "suburban"
    },
    {
      "patient_id": "P00970",
      "doctor_id": "D05",
      "patient_age": 77,
      "patient_sex": "F",
      "date_of_death": "2022-10-25",
      "hour_of_death": 14,
      "home_visit_same_day": 1,
      "place_of_death": "home",
      "cause_category": "respiratory",
      "doctor_practice_type": "suburban"
    },
    {
      "patient_id": "P00995",
      "doctor_id": "D05",
      "patient_age": 82,
      "patient_sex": "F",
      "date_of_death": "2022-04-11",
      "hour_of_death": 8,
      "home_visit_same_day": 0,
      "place_of_death": "home",
      "cause_category": "cancer",
      "doctor_practice_type": "suburban"
    },
    {
      "patient_id": "P01001",
      "doctor_id": "D05",
      "patient_age": 76,
      "patient_sex": "F",
      "date_of_death": "2023-02-08",
      "hour_of_death": 9,
      "home_visit_same_day": 0,
      "place_of_death": "hospital",
      "cause_category": "cardiovascular",
      "doctor_practice_type": "suburban"
    },
    {
      "patient_id": "P01007",
      "doctor_id": "D05",
      "patient_age": 87,
      "patient_sex": "M",
      "date_of_death": "2022-05-24",
      "hour_of_death": 10,
      "home_visit_same_day": 0,
      "place_of_death": "hospital",
      "cause_category": "cancer",
      "doctor_practice_type": "suburban"
    },
    {
      "patient_id": "P01012",
      "doctor_id": "D05",
      "patient_age": 71,
      "patient_sex": "F",
      "date_of_death": "2023-04-02",
      "hour_of_death": 0,
      "home_visit_same_day": 0,
      "place_of_death": "care_home",
      "cause_category": "frailty",
      "doctor_practice_type": "suburban"
    },
    {
      "patient_id": "P01033",
      "doctor_id": "D05",
      "patient_age": 82,
      "patient_sex": "F",
      "date_of_death": "2023-07-17",
      "hour_of_death": 8,
      "home_visit_same_day": 1,
      "place_of_death": "hospital",
      "cause_category": "cancer",
      "doctor_practice_type": "suburban"
    },
    {
      "patient_id": "P01036",
      "doctor_id": "D05",
      "patient_age": 75,
      "patient_sex": "F",
      "date_of_death": "2022-06-29",
      "hour_of_death": 5,
      "home_visit_same_day": 0,
      "place_of_death": "care_home",
      "cause_category": "cardiovascular",
      "doctor_practice_type": "suburban"
    },
    {
      "patient_id": "P01054",
      "doctor_id": "D05",
      "patient_age": 78,
      "patient_sex": "F",
      "date_of_death": "2023-06-05",
      "hour_of_death": 14,
      "home_visit_same_day": 0,
      "place_of_death": "hospital",
      "cause_category": "frailty",
      "doctor_practice_type": "suburban"
    },
    {
      "patient_id": "P01057",
      "doctor_id": "D05",
      "patient_age": 80,
      "patient_sex": "M",
      "date_of_death": "2023-08-18",
      "hour_of_death": 4,
      "home_visit_same_day": 0,
      "place_of_death": "hospital",
      "cause_category": "cardiovascular",
      "doctor_practice_type": "suburban"
    },
    {
      "patient_id": "P01074",
      "doctor_id": "D05",
      "patient_age": 75,
      "patient_sex": "F",
      "date_of_death": "2022-02-11",
      "hour_of_death": 2,
      "home_visit_same_day": 0,
      "place_of_death": "hospital",
      "cause_category": "cardiovascular",
      "doctor_practice_type": "suburban"
    },
    {
      "patient_id": "P01089",
      "doctor_id": "D05",
      "patient_age": 79,
      "patient_sex": "F",
      "date_of_death": "2023-12-10",
      "hour_of_death": 10,
      "home_visit_same_day": 1,
      "place_of_death": "home",
      "cause_category": "respiratory",
      "doctor_practice_type": "suburban"
    },
    {
      "patient_id": "P01116",
      "doctor_id": "D05",
      "patient_age": 98,
      "patient_sex": "F",
      "date_of_death": "2023-06-01",
      "hour_of_death": 3,
      "home_visit_same_day": 0,
      "place_of_death": "home",
      "cause_category": "cancer",
      "doctor_practice_type": "suburban"
    },
    {
      "patient_id": "P01132",
      "doctor_id": "D05",
      "patient_age": 91,
      "patient_sex": "M",
      "date_of_death": "2022-01-21",
      "hour_of_death": 7,
      "home_visit_same_day": 0,
      "place_of_death": "hospital",
      "cause_category": "cancer",
      "doctor_practice_type": "suburban"
    },
    {
      "patient_id": "P01156",
      "doctor_id": "D05",
      "patient_age": 81,
      "patient_sex": "M",
      "date_of_death": "2023-04-03",
      "hour_of_death": 7,
      "home_visit_same_day": 0,
      "place_of_death": "care_home",
      "cause_category": "cardiovascular",
      "doctor_practice_type": "suburban"
    },
    {
      "patient_id": "P01167",
      "doctor_id": "D05",
      "patient_age": 84,
      "patient_sex": "F",
      "date_of_death": "2023-08-20",
      "hour_of_death": 9,
      "home_visit_same_day": 0,
      "place_of_death": "hospital",
      "cause_category": "cardiovascular",
      "doctor_practice_type": "suburban"
    },
    {
      "patient_id": "P01212",
      "doctor_id": "D06",
      "patient_age": 80,
      "patient_sex": "F",
      "date_of_death": "2022-11-19",
      "hour_of_death": 22,
      "home_visit_same_day": 0,
      "place_of_death": "hospital",
      "cause_category": "cardiovascular",
      "doctor_practice_type": "suburban"
    },
    {
      "patient_id": "P01218",
      "doctor_id": "D06",
      "patient_age": 58,
      "patient_sex": "M",
      "date_of_death": "2022-01-02",
      "hour_of_death": 18,
      "home_visit_same_day": 0,
      "place_of_death": "hospital",
      "cause_category": "cancer",
      "doctor_practice_type": "suburban"
    },
    {
      "patient_id": "P01240",
      "doctor_id": "D06",
      "patient_age": 66,
      "patient_sex": "M",
      "date_of_death": "2022-09-16",
      "hour_of_death": 1,
      "home_visit_same_day": 0,
      "place_of_death": "care_home",
      "cause_category": "other",
      "doctor_practice_type": "suburban"
    },
    {
      "patient_id": "P01246",
      "doctor_id": "D06",
      "patient_age": 74,
      "patient_sex": "F",
      "date_of_death": "2022-07-01",
      "hour_of_death": 4,
      "home_visit_same_day": 0,
      "place_of_death": "home",
      "cause_category": "cardiovascular",
      "doctor_practice_type": "suburban"
    },
    {
      "patient_id": "P01295",
      "doctor_id": "D06",
      "patient_age": 73,
      "patient_sex": "M",
      "date_of_death": "2023-01-31",
      "hour_of_death": 13,
      "home_visit_same_day": 1,
      "place_of_death": "care_home",
      "cause_category": "respiratory",
      "doctor_practice_type": "suburban"
    },
    {
      "patient_id": "P01301",
      "doctor_id": "D06",
      "patient_age": 81,
      "patient_sex": "M",
      "date_of_death": "2023-01-24",
      "hour_of_death": 13,
      "home_visit_same_day": 1,
      "place_of_death": "care_home",
      "cause_category": "cancer",
      "doctor_practice_type": "suburban"
    },
    {
      "patient_id": "P01313",
      "doctor_id": "D06",
      "patient_age": 90,
      "patient_sex": "M",
      "date_of_death": "2023-08-05",
      "hour_of_death": 3,
      "home_visit_same_day": 0,
      "place_of_death": "home",
      "cause_category": "cardiovascular",
      "doctor_practice_type": "suburban"
    },
    {
      "patient_id": "P01374",
      "doctor_id": "D06",
      "patient_age": 95,
      "patient_sex": "M",
      "date_of_death": "2022-04-15",
      "hour_of_death": 6,
      "home_visit_same_day": 0,
      "place_of_death": "home",
      "cause_category": "respiratory",
      "doctor_practice_type": "suburban"
    },
    {
      "patient_id": "P01375",
      "doctor_id": "D06",
      "patient_age": 67,
      "patient_sex": "M",
      "date_of_death": "2023-01-16",
      "hour_of_death": 19,
      "home_visit_same_day": 0,
      "place_of_death": "hospital",
      "cause_category": "cardiovascular",
      "doctor_practice_type": "suburban"
    },
    {
      "patient_id": "P01384",
      "doctor_id": "D06",
      "patient_age": 71,
      "patient_sex": "M",
      "date_of_death": "2022-10-04",
      "hour_of_death": 6,
      "home_visit_same_day": 0,
      "place_of_death": "care_home",
      "cause_category": "frailty",
      "doctor_practice_type": "suburban"
    },
    {
      "patient_id": "P01390",
      "doctor_id": "D06",
      "patient_age": 83,
      "patient_sex": "F",
      "date_of_death": "2022-01-20",
      "hour_of_death": 7,
      "home_visit_same_day": 0,
      "place_of_death": "home",
      "cause_category": "cancer",
      "doctor_practice_type": "suburban"
    },
    {
      "patient_id": "P01434",
      "doctor_id": "D07",
      "patient_age": 76,
      "patient_sex": "F",
      "date_of_death": "2023-09-14",
      "hour_of_death": 7,
      "home_visit_same_day": 0,
      "place_of_death": "hospital",
      "cause_category": "frailty",
      "doctor_practice_type": "urban"
    },
    {
      "patient_id": "P01443",
      "doctor_id": "D07",
      "patient_age": 72,
      "patient_sex": "F",
      "date_of_death": "2023-08-23",
      "hour_of_death": 3,
      "home_visit_same_day": 0,
      "place_of_death": "home",
      "cause_category": "other",
      "doctor_practice_type": "urban"
    },
    {
      "patient_id": "P01444",
      "doctor_id": "D07",
      "patient_age": 88,
      "patient_sex": "F",
      "date_of_death": "2023-10-12",
      "hour_of_death": 12,
      "home_visit_same_day": 0,
      "place_of_death": "home",
      "cause_category": "cardiovascular",
      "doctor_practice_type": "urban"
    },
    {
      "patient_id": "P01472",
      "doctor_id": "D07",
      "patient_age": 64,
      "patient_sex": "M",
      "date_of_death": "2023-09-07",
      "hour_of_death": 13,
      "home_visit_same_day": 1,
      "place_of_death": "hospital",
      "cause_category": "cancer",
      "doctor_practice_type": "urban"
    },
    {
      "patient_id": "P01479",
      "doctor_id": "D07",
      "patient_age": 73,
      "patient_sex": "M",
      "date_of_death": "2023-07-14",
      "hour_of_death": 16,
      "home_visit_same_day": 1,
      "place_of_death": "care_home",
      "cause_category": "cancer",
      "doctor_practice_type": "urban"
    },
    {
      "patient_id": "P01487",
      "doctor_id": "D07",
      "patient_age": 66,
      "patient_sex": "F",
      "date_of_death": "2023-09-29",
      "hour_of_death": 13,
      "home_visit_same_day": 0,
      "place_of_death": "home",
      "cause_category": "respiratory",
      "doctor_practice_type": "urban"
    },
    {
      "patient_id": "P01521",
      "doctor_id": "D07",
      "patient_age": 62,
      "patient_sex": "F",
      "date_of_death": "2022-04-22",
      "hour_of_death": 9,
      "home_visit_same_day": 0,
      "place_of_death": "hospital",
      "cause_category": "cardiovascular",
      "doctor_practice_type": "urban"
    },
    {
      "patient_id": "P01585",
      "doctor_id": "D08",
      "patient_age": 69,
      "patient_sex": "M",
      "date_of_death": "2022-10-08",
      "hour_of_death": 8,
      "home_visit_same_day": 0,
      "place_of_death": "home",
      "cause_category": "respiratory",
      "doctor_practice_type": "urban"
    },
    {
      "patient_id": "P01602",
      "doctor_id": "D08",
      "patient_age": 73,
      "patient_sex": "F",
      "date_of_death": "2023-11-27",
      "hour_of_death": 0,
      "home_visit_same_day": 0,
      "place_of_death": "home",
      "cause_category": "frailty",
      "doctor_practice_type": "urban"
    },
    {
      "patient_id": "P01604",
      "doctor_id": "D08",
      "patient_age": 94,
      "patient_sex": "F",
      "date_of_death": "2023-01-30",
      "hour_of_death": 11,
      "home_visit_same_day": 1,
      "place_of_death": "hospital",
      "cause_category": "cancer",
      "doctor_practice_type": "urban"
    },
    {
      "patient_id": "P01609",
      "doctor_id": "D08",
      "patient_age": 82,
      "patient_sex": "F",
      "date_of_death": "2023-08-23",
      "hour_of_death": 22,
      "home_visit_same_day": 0,
      "place_of_death": "hospital",
      "cause_category": "frailty",
      "doctor_practice_type": "urban"
    },
    {
      "patient_id": "P01620",
      "doctor_id": "D08",
      "patient_age": 77,
      "patient_sex": "F",
      "date_of_death": "2023-08-12",
      "hour_of_death": 0,
      "home_visit_same_day": 0,
      "place_of_death": "home",
      "cause_category": "frailty",
      "doctor_practice_type": "urban"
    },
    {
      "patient_id": "P01643",
      "doctor_id": "D08",
      "patient_age": 79,
      "patient_sex": "M",
      "date_of_death": "2022-03-09",
      "hour_of_death": 11,
      "home_visit_same_day": 1,
      "place_of_death": "home",
      "cause_category": "respiratory",
      "doctor_practice_type": "urban"
    },
    {
      "patient_id": "P01647",
      "doctor_id": "D08",
      "patient_age": 72,
      "patient_sex": "M",
      "date_of_death": "2023-09-14",
      "hour_of_death": 3,
      "home_visit_same_day": 0,
      "place_of_death": "care_home",
      "cause_category": "cardiovascular",
      "doctor_practice_type": "urban"
    },
    {
      "patient_id": "P01649",
      "doctor_id": "D08",
      "patient_age": 78,
      "patient_sex": "F",
      "date_of_death": "2023-03-05",
      "hour_of_death": 18,
      "home_visit_same_day": 0,
      "place_of_death": "hospital",
      "cause_category": "cancer",
      "doctor_practice_type": "urban"
    },
    {
      "patient_id": "P01660",
      "doctor_id": "D08",
      "patient_age": 78,
      "patient_sex": "F",
      "date_of_death": "2022-04-03",
      "hour_of_death": 7,
      "home_visit_same_day": 0,
      "place_of_death": "home",
      "cause_category": "cardiovascular",
      "doctor_practice_type": "urban"
    },
    {
      "patient_id": "P01666",
      "doctor_id": "D08",
      "patient_age": 72,
      "patient_sex": "M",
      "date_of_death": "2022-09-09",
      "hour_of_death": 5,
      "home_visit_same_day": 0,
      "place_of_death": "care_home",
      "cause_category": "frailty",
      "doctor_practice_type": "urban"
    },
    {
      "patient_id": "P01679",
      "doctor_id": "D08",
      "patient_age": 89,
      "patient_sex": "M",
      "date_of_death": "2023-10-11",
      "hour_of_death": 6,
      "home_visit_same_day": 0,
      "place_of_death": "home",
      "cause_category": "cardiovascular",
      "doctor_practice_type": "urban"
    },
    {
      "patient_id": "P01712",
      "doctor_id": "D08",
      "patient_age": 68,
      "patient_sex": "M",
      "date_of_death": "2022-07-27",
      "hour_of_death": 7,
      "home_visit_same_day": 1,
      "place_of_death": "care_home",
      "cause_category": "other",
      "doctor_practice_type": "urban"
    },
    {
      "patient_id": "P01723",
      "doctor_id": "D08",
      "patient_age": 82,
      "patient_sex": "M",
      "date_of_death": "2022-03-18",
      "hour_of_death": 11,
      "home_visit_same_day": 1,
      "place_of_death": "home",
      "cause_category": "cardiovascular",
      "doctor_practice_type": "urban"
    },
    {
      "patient_id": "P01768",
      "doctor_id": "D08",
      "patient_age": 84,
      "patient_sex": "F",
      "date_of_death": "2022-12-19",
      "hour_of_death": 13,
      "home_visit_same_day": 0,
      "place_of_death": "care_home",
      "cause_category": "cancer",
      "doctor_practice_type": "urban"
    },
    {
      "patient_id": "P01858",
      "doctor_id": "D09",
      "patient_age": 84,
      "patient_sex": "M",
      "date_of_death": "2023-10-26",
      "hour_of_death": 5,
      "home_visit_same_day": 0,
      "place_of_death": "hospital",
      "cause_category": "frailty",
      "doctor_practice_type": "rural"
    },
    {
      "patient_id": "P01896",
      "doctor_id": "D09",
      "patient_age": 79,
      "patient_sex": "M",
      "date_of_death": "2023-06-07",
      "hour_of_death": 13,
      "home_visit_same_day": 0,
      "place_of_death": "hospital",
      "cause_category": "frailty",
      "doctor_practice_type": "rural"
    },
    {
      "patient_id": "P01928",
      "doctor_id": "D09",
      "patient_age": 65,
      "patient_sex": "M",
      "date_of_death": "2022-11-08",
      "hour_of_death": 9,
      "home_visit_same_day": 0,
      "place_of_death": "hospital",
      "cause_category": "other",
      "doctor_practice_type": "rural"
    },
    {
      "patient_id": "P01954",
      "doctor_id": "D09",
      "patient_age": 89,
      "patient_sex": "M",
      "date_of_death": "2023-08-02",
      "hour_of_death": 14,
      "home_visit_same_day": 1,
      "place_of_death": "home",
      "cause_category": "cardiovascular",
      "doctor_practice_type": "rural"
    },
    {
      "patient_id": "P01963",
      "doctor_id": "D09",
      "patient_age": 62,
      "patient_sex": "M",
      "date_of_death": "2023-06-14",
      "hour_of_death": 1,
      "home_visit_same_day": 0,
      "place_of_death": "hospital",
      "cause_category": "respiratory",
      "doctor_practice_type": "rural"
    },
    {
      "patient_id": "P01980",
      "doctor_id": "D09",
      "patient_age": 80,
      "patient_sex": "F",
      "date_of_death": "2022-02-13",
      "hour_of_death": 9,
      "home_visit_same_day": 1,
      "place_of_death": "hospital",
      "cause_category": "respiratory",
      "doctor_practice_type": "rural"
    },
    {
      "patient_id": "P01997",
      "doctor_id": "D09",
      "patient_age": 83,
      "patient_sex": "F",
      "date_of_death": "2022-11-20",
      "hour_of_death": 4,
      "home_visit_same_day": 0,
      "place_of_death": "care_home",
      "cause_category": "cancer",
      "doctor_practice_type": "rural"
    },
    {
      "patient_id": "P02001",
      "doctor_id": "D09",
      "patient_age": 70,
      "patient_sex": "M",
      "date_of_death": "2023-01-28",
      "hour_of_death": 17,
      "home_visit_same_day": 0,
      "place_of_death": "hospital",
      "cause_category": "frailty",
      "doctor_practice_type": "rural"
    },
    {
      "patient_id": "P02006",
      "doctor_id": "D09",
      "patient_age": 76,
      "patient_sex": "F",
      "date_of_death": "2023-10-11",
      "hour_of_death": 4,
      "home_visit_same_day": 0,
      "place_of_death": "home",
      "cause_category": "cancer",
      "doctor_practice_type": "rural"
    },
    {
      "patient_id": "P02015",
      "doctor_id": "D09",
      "patient_age": 50,
      "patient_sex": "F",
      "date_of_death": "2023-08-14",
      "hour_of_death": 7,
      "home_visit_same_day": 0,
      "place_of_death": "care_home",
      "cause_category": "frailty",
      "doctor_practice_type": "rural"
    },
    {
      "patient_id": "P02018",
      "doctor_id": "D09",
      "patient_age": 79,
      "patient_sex": "F",
      "date_of_death": "2022-03-12",
      "hour_of_death": 18,
      "home_visit_same_day": 0,
      "place_of_death": "care_home",
      "cause_category": "cancer",
      "doctor_practice_type": "rural"
    },
    {
      "patient_id": "P02031",
      "doctor_id": "D09",
      "patient_age": 80,
      "patient_sex": "F",
      "date_of_death": "2023-04-09",
      "hour_of_death": 13,
      "home_visit_same_day": 1,
      "place_of_death": "home",
      "cause_category": "cardiovascular",
      "doctor_practice_type": "rural"
    },
    {
      "patient_id": "P02034",
      "doctor_id": "D09",
      "patient_age": 92,
      "patient_sex": "F",
      "date_of_death": "2023-04-16",
      "hour_of_death": 9,
      "home_visit_same_day": 1,
      "place_of_death": "hospital",
      "cause_category": "other",
      "doctor_practice_type": "rural"
    },
    {
      "patient_id": "P02049",
      "doctor_id": "D10",
      "patient_age": 81,
      "patient_sex": "F",
      "date_of_death": "2023-01-30",
      "hour_of_death": 12,
      "home_visit_same_day": 0,
      "place_of_death": "hospital",
      "cause_category": "frailty",
      "doctor_practice_type": "urban"
    },
    {
      "patient_id": "P02050",
      "doctor_id": "D10",
      "patient_age": 72,
      "patient_sex": "M",
      "date_of_death": "2022-12-27",
      "hour_of_death": 10,
      "home_visit_same_day": 0,
      "place_of_death": "home",
      "cause_category": "cardiovascular",
      "doctor_practice_type": "urban"
    },
    {
      "patient_id": "P02062",
      "doctor_id": "D10",
      "patient_age": 82,
      "patient_sex": "F",
      "date_of_death": "2022-03-22",
      "hour_of_death": 15,
      "home_visit_same_day": 0,
      "place_of_death": "home",
      "cause_category": "respiratory",
      "doctor_practice_type": "urban"
    },
    {
      "patient_id": "P02071",
      "doctor_id": "D10",
      "patient_age": 73,
      "patient_sex": "M",
      "date_of_death": "2022-09-17",
      "hour_of_death": 23,
      "home_visit_same_day": 0,
      "place_of_death": "hospital",
      "cause_category": "cardiovascular",
      "doctor_practice_type": "urban"
    },
    {
      "patient_id": "P02079",
      "doctor_id": "D10",
      "patient_age": 84,
      "patient_sex": "F",
      "date_of_death": "2023-04-02",
      "hour_of_death": 4,
      "home_visit_same_day": 0,
      "place_of_death": "hospital",
      "cause_category": "respiratory",
      "doctor_practice_type": "urban"
    },
    {
      "patient_id": "P02116",
      "doctor_id": "D10",
      "patient_age": 78,
      "patient_sex": "M",
      "date_of_death": "2022-10-14",
      "hour_of_death": 12,
      "home_visit_same_day": 0,
      "place_of_death": "hospital",
      "cause_category": "cardiovascular",
      "doctor_practice_type": "urban"
    },
    {
      "patient_id": "P02125",
      "doctor_id": "D10",
      "patient_age": 94,
      "patient_sex": "F",
      "date_of_death": "2023-08-09",
      "hour_of_death": 11,
      "home_visit_same_day": 0,
      "place_of_death": "home",
      "cause_category": "other",
      "doctor_practice_type": "urban"
    },
    {
      "patient_id": "P02146",
      "doctor_id": "D10",
      "patient_age": 75,
      "patient_sex": "M",
      "date_of_death": "2023-01-04",
      "hour_of_death": 11,
      "home_visit_same_day": 1,
      "place_of_death": "hospital",
      "cause_category": "cardiovascular",
      "doctor_practice_type": "urban"
    },
    {
      "patient_id": "P02147",
      "doctor_id": "D10",
      "patient_age": 98,
      "patient_sex": "F",
      "date_of_death": "2022-04-23",
      "hour_of_death": 7,
      "home_visit_same_day": 1,
      "place_of_death": "care_home",
      "cause_category": "frailty",
      "doctor_practice_type": "urban"
    },
    {
      "patient_id": "P02153",
      "doctor_id": "D10",
      "patient_age": 72,
      "patient_sex": "F",
      "date_of_death": "2023-07-26",
      "hour_of_death": 19,
      "home_visit_same_day": 0,
      "place_of_death": "home",
      "cause_category": "cancer",
      "doctor_practice_type": "urban"
    },
    {
      "patient_id": "P02164",
      "doctor_id": "D10",
      "patient_age": 87,
      "patient_sex": "F",
      "date_of_death": "2023-07-04",
      "hour_of_death": 21,
      "home_visit_same_day": 1,
      "place_of_death": "hospital",
      "cause_category": "cancer",
      "doctor_practice_type": "urban"
    },
    {
      "patient_id": "P02169",
      "doctor_id": "D10",
      "patient_age": 80,
      "patient_sex": "F",
      "date_of_death": "2022-03-31",
      "hour_of_death": 20,
      "home_visit_same_day": 0,
      "place_of_death": "care_home",
      "cause_category": "cancer",
      "doctor_practice_type": "urban"
    },
    {
      "patient_id": "P02203",
      "doctor_id": "D10",
      "patient_age": 59,
      "patient_sex": "F",
      "date_of_death": "2022-05-23",
      "hour_of_death": 3,
      "home_visit_same_day": 0,
      "place_of_death": "home",
      "cause_category": "cancer",
      "doctor_practice_type": "urban"
    },
    {
      "patient_id": "P02208",
      "doctor_id": "D10",
      "patient_age": 91,
      "patient_sex": "M",
      "date_of_death": "2022-08-31",
      "hour_of_death": 21,
      "home_visit_same_day": 0,
      "place_of_death": "hospital",
      "cause_category": "cancer",
      "doctor_practice_type": "urban"
    },
    {
      "patient_id": "P02212",
      "doctor_id": "D10",
      "patient_age": 77,
      "patient_sex": "F",
      "date_of_death": "2022-02-28",
      "hour_of_death": 16,
      "home_visit_same_day": 1,
      "place_of_death": "home",
      "cause_category": "cancer",
      "doctor_practice_type": "urban"
    },
    {
      "patient_id": "P02232",
      "doctor_id": "D10",
      "patient_age": 70,
      "patient_sex": "F",
      "date_of_death": "2022-07-14",
      "hour_of_death": 7,
      "home_visit_same_day": 1,
      "place_of_death": "hospital",
      "cause_category": "cardiovascular",
      "doctor_practice_type": "urban"
    },
    {
      "patient_id": "P02251",
      "doctor_id": "D10",
      "patient_age": 72,
      "patient_sex": "M",
      "date_of_death": "2023-07-29",
      "hour_of_death": 7,
      "home_visit_same_day": 1,
      "place_of_death": "home",
      "cause_category": "cardiovascular",
      "doctor_practice_type": "urban"
    },
    {
      "patient_id": "P02260",
      "doctor_id": "D10",
      "patient_age": 66,
      "patient_sex": "F",
      "date_of_death": "2022-12-05",
      "hour_of_death": 3,
      "home_visit_same_day": 0,
      "place_of_death": "care_home",
      "cause_category": "other",
      "doctor_practice_type": "urban"
    },
    {
      "patient_id": "P02281",
      "doctor_id": "D11",
      "patient_age": 75,
      "patient_sex": "M",
      "date_of_death": "2023-02-19",
      "hour_of_death": 23,
      "home_visit_same_day": 0,
      "place_of_death": "care_home",
      "cause_category": "cardiovascular",
      "doctor_practice_type": "suburban"
    },
    {
      "patient_id": "P02286",
      "doctor_id": "D11",
      "patient_age": 59,
      "patient_sex": "M",
      "date_of_death": "2023-06-12",
      "hour_of_death": 7,
      "home_visit_same_day": 0,
      "place_of_death": "home",
      "cause_category": "cardiovascular",
      "doctor_practice_type": "suburban"
    },
    {
      "patient_id": "P02301",
      "doctor_id": "D11",
      "patient_age": 78,
      "patient_sex": "F",
      "date_of_death": "2023-06-03",
      "hour_of_death": 1,
      "home_visit_same_day": 0,
      "place_of_death": "hospital",
      "cause_category": "cancer",
      "doctor_practice_type": "suburban"
    },
    {
      "patient_id": "P02322",
      "doctor_id": "D11",
      "patient_age": 68,
      "patient_sex": "M",
      "date_of_death": "2023-04-29",
      "hour_of_death": 11,
      "home_visit_same_day": 0,
      "place_of_death": "hospital",
      "cause_category": "cancer",
      "doctor_practice_type": "suburban"
    },
    {
      "patient_id": "P02350",
      "doctor_id": "D11",
      "patient_age": 81,
      "patient_sex": "M",
      "date_of_death": "2022-07-13",
      "hour_of_death": 7,
      "home_visit_same_day": 0,
      "place_of_death": "hospital",
      "cause_category": "cardiovascular",
      "doctor_practice_type": "suburban"
    },
    {
      "patient_id": "P02351",
      "doctor_id": "D11",
      "patient_age": 86,
      "patient_sex": "M",
      "date_of_death": "2023-05-11",
      "hour_of_death": 13,
      "home_visit_same_day": 0,
      "place_of_death": "hospital",
      "cause_category": "respiratory",
      "doctor_practice_type": "suburban"
    },
    {
      "patient_id": "P02396",
      "doctor_id": "D11",
      "patient_age": 80,
      "patient_sex": "F",
      "date_of_death": "2022-06-30",
      "hour_of_death": 2,
      "home_visit_same_day": 0,
      "place_of_death": "home",
      "cause_category": "frailty",
      "doctor_practice_type": "suburban"
    },
    {
      "patient_id": "P02400",
      "doctor_id": "D11",
      "patient_age": 54,
      "patient_sex": "M",
      "date_of_death": "2022-02-19",
      "hour_of_death": 12,
      "home_visit_same_day": 1,
      "place_of_death": "hospital",
      "cause_category": "cardiovascular",
      "doctor_practice_type": "suburban"
    },
    {
      "patient_id": "P02487",
      "doctor_id": "D12",
      "patient_age": 68,
      "patient_sex": "M",
      "date_of_death": "2022-06-26",
      "hour_of_death": 7,
      "home_visit_same_day": 0,
      "place_of_death": "care_home",
      "cause_category": "cardiovascular",
      "doctor_practice_type": "urban"
    },
    {
      "patient_id": "P02495",
      "doctor_id": "D12",
      "patient_age": 82,
      "patient_sex": "F",
      "date_of_death": "2022-05-13",
      "hour_of_death": 6,
      "home_visit_same_day": 0,
      "place_of_death": "care_home",
      "cause_category": "cancer",
      "doctor_practice_type": "urban"
    },
    {
      "patient_id": "P02498",
      "doctor_id": "D12",
      "patient_age": 73,
      "patient_sex": "F",
      "date_of_death": "2023-05-08",
      "hour_of_death": 20,
      "home_visit_same_day": 0,
      "place_of_death": "home",
      "cause_category": "cancer",
      "doctor_practice_type": "urban"
    },
    {
      "patient_id": "P02518",
      "doctor_id": "D12",
      "patient_age": 69,
      "patient_sex": "F",
      "date_of_death": "2022-04-16",
      "hour_of_death": 14,
      "home_visit_same_day": 0,
      "place_of_death": "hospital",
      "cause_category": "respiratory",
      "doctor_practice_type": "urban"
    },
    {
      "patient_id": "P02555",
      "doctor_id": "D12",
      "patient_age": 68,
      "patient_sex": "F",
      "date_of_death": "2022-02-24",
      "hour_of_death": 11,
      "home_visit_same_day": 0,
      "place_of_death": "hospital",
      "cause_category": "frailty",
      "doctor_practice_type": "urban"
    },
    {
      "patient_id": "P02586",
      "doctor_id": "D12",
      "patient_age": 83,
      "patient_sex": "M",
      "date_of_death": "2022-05-30",
      "hour_of_death": 9,
      "home_visit_same_day": 0,
      "place_of_death": "care_home",
      "cause_category": "cancer",
      "doctor_practice_type": "urban"
    },
    {
      "patient_id": "P02622",
      "doctor_id": "D12",
      "patient_age": 72,
      "patient_sex": "M",
      "date_of_death": "2022-09-27",
      "hour_of_death": 12,
      "home_visit_same_day": 0,
      "place_of_death": "home",
      "cause_category": "cancer",
      "doctor_practice_type": "urban"
    },
    {
      "patient_id": "P02652",
      "doctor_id": "D12",
      "patient_age": 79,
      "patient_sex": "F",
      "date_of_death": "2022-02-16",
      "hour_of_death": 23,
      "home_visit_same_day": 0,
      "place_of_death": "hospital",
      "cause_category": "frailty",
      "doctor_practice_type": "urban"
    },
    {
      "patient_id": "P02663",
      "doctor_id": "D12",
      "patient_age": 76,
      "patient_sex": "M",
      "date_of_death": "2022-03-20",
      "hour_of_death": 22,
      "home_visit_same_day": 0,
      "place_of_death": "home",
      "cause_category": "other",
      "doctor_practice_type": "urban"
    },
    {
      "patient_id": "P02712",
      "doctor_id": "D13",
      "patient_age": 75,
      "patient_sex": "M",
      "date_of_death": "2022-08-30",
      "hour_of_death": 15,
      "home_visit_same_day": 1,
      "place_of_death": "home",
      "cause_category": "frailty",
      "doctor_practice_type": "urban"
    },
    {
      "patient_id": "P02716",
      "doctor_id": "D13",
      "patient_age": 72,
      "patient_sex": "M",
      "date_of_death": "2022-06-19",
      "hour_of_death": 12,
      "home_visit_same_day": 1,
      "place_of_death": "home",
      "cause_category": "frailty",
      "doctor_practice_type": "urban"
    },
    {
      "patient_id": "P02727",
      "doctor_id": "D13",
      "patient_age": 58,
      "patient_sex": "M",
      "date_of_death": "2022-03-20",
      "hour_of_death": 15,
      "home_visit_same_day": 1,
      "place_of_death": "home",
      "cause_category": "cancer",
      "doctor_practice_type": "urban"
    },
    {
      "patient_id": "P02742",
      "doctor_id": "D13",
      "patient_age": 79,
      "patient_sex": "M",
      "date_of_death": "2022-05-01",
      "hour_of_death": 14,
      "home_visit_same_day": 0,
      "place_of_death": "hospital",
      "cause_category": "cardiovascular",
      "doctor_practice_type": "urban"
    },
    {
      "patient_id": "P02743",
      "doctor_id": "D13",
      "patient_age": 66,
      "patient_sex": "F",
      "date_of_death": "2023-10-02",
      "hour_of_death": 12,
      "home_visit_same_day": 0,
      "place_of_death": "home",
      "cause_category": "frailty",
      "doctor_practice_type": "urban"
    },
    {
      "patient_id": "P02750",
      "doctor_id": "D13",
      "patient_age": 62,
      "patient_sex": "F",
      "date_of_death": "2022-12-01",
      "hour_of_death": 16,
      "home_visit_same_day": 1,
      "place_of_death": "home",
      "cause_category": "cancer",
      "doctor_practice_type": "urban"
    },
    {
      "patient_id": "P02761",
      "doctor_id": "D13",
      "patient_age": 86,
      "patient_sex": "F",
      "date_of_death": "2023-02-27",
      "hour_of_death": 15,
      "home_visit_same_day": 1,
      "place_of_death": "home",
      "cause_category": "cardiovascular",
      "doctor_practice_type": "urban"
    },
    {
      "patient_id": "P02767",
      "doctor_id": "D13",
      "patient_age": 60,
      "patient_sex": "M",
      "date_of_death": "2022-11-22",
      "hour_of_death": 16,
      "home_visit_same_day": 1,
      "place_of_death": "home",
      "cause_category": "respiratory",
      "doctor_practice_type": "urban"
    },
    {
      "patient_id": "P02776",
      "doctor_id": "D13",
      "patient_age": 84,
      "patient_sex": "M",
      "date_of_death": "2023-10-15",
      "hour_of_death": 12,
      "home_visit_same_day": 1,
      "place_of_death": "home",
      "cause_category": "other",
      "doctor_practice_type": "urban"
    },
    {
      "patient_id": "P02780",
      "doctor_id": "D13",
      "patient_age": 76,
      "patient_sex": "M",
      "date_of_death": "2023-12-15",
      "hour_of_death": 15,
      "home_visit_same_day": 1,
      "place_of_death": "home",
      "cause_category": "respiratory",
      "doctor_practice_type": "urban"
    },
    {
      "patient_id": "P02798",
      "doctor_id": "D13",
      "patient_age": 86,
      "patient_sex": "M",
      "date_of_death": "2022-06-25",
      "hour_of_death": 13,
      "home_visit_same_day": 1,
      "place_of_death": "care_home",
      "cause_category": "respiratory",
      "doctor_practice_type": "urban"
    },
    {
      "patient_id": "P02819",
      "doctor_id": "D13",
      "patient_age": 84,
      "patient_sex": "F",
      "date_of_death": "2023-04-27",
      "hour_of_death": 13,
      "home_visit_same_day": 1,
      "place_of_death": "home",
      "cause_category": "respiratory",
      "doctor_practice_type": "urban"
    },
    {
      "patient_id": "P02820",
      "doctor_id": "D13",
      "patient_age": 67,
      "patient_sex": "M",
      "date_of_death": "2022-03-28",
      "hour_of_death": 10,
      "home_visit_same_day": 0,
      "place_of_death": "home",
      "cause_category": "respiratory",
      "doctor_practice_type": "urban"
    },
    {
      "patient_id": "P02821",
      "doctor_id": "D13",
      "patient_age": 80,
      "patient_sex": "F",
      "date_of_death": "2022-05-15",
      "hour_of_death": 15,
      "home_visit_same_day": 1,
      "place_of_death": "home",
      "cause_category": "cardiovascular",
      "doctor_practice_type": "urban"
    },
    {
      "patient_id": "P02826",
      "doctor_id": "D13",
      "patient_age": 63,
      "patient_sex": "F",
      "date_of_death": "2022-09-12",
      "hour_of_death": 14,
      "home_visit_same_day": 1,
      "place_of_death": "hospital",
      "cause_category": "cardiovascular",
      "doctor_practice_type": "urban"
    },
    {
      "patient_id": "P02850",
      "doctor_id": "D13",
      "patient_age": 50,
      "patient_sex": "M",
      "date_of_death": "2023-02-28",
      "hour_of_death": 15,
      "home_visit_same_day": 1,
      "place_of_death": "home",
      "cause_category": "cardiovascular",
      "doctor_practice_type": "urban"
    },
    {
      "patient_id": "P02866",
      "doctor_id": "D13",
      "patient_age": 85,
      "patient_sex": "M",
      "date_of_death": "2023-02-03",
      "hour_of_death": 16,
      "home_visit_same_day": 1,
      "place_of_death": "care_home",
      "cause_category": "respiratory",
      "doctor_practice_type": "urban"
    },
    {
      "patient_id": "P02872",
      "doctor_id": "D13",
      "patient_age": 55,
      "patient_sex": "M",
      "date_of_death": "2022-06-10",
      "hour_of_death": 13,
      "home_visit_same_day": 1,
      "place_of_death": "home",
      "cause_category": "respiratory",
      "doctor_practice_type": "urban"
    },
    {
      "patient_id": "P02881",
      "doctor_id": "D13",
      "patient_age": 69,
      "patient_sex": "F",
      "date_of_death": "2023-12-22",
      "hour_of_death": 15,
      "home_visit_same_day": 0,
      "place_of_death": "hospital",
      "cause_category": "cardiovascular",
      "doctor_practice_type": "urban"
    },
    {
      "patient_id": "P02900",
      "doctor_id": "D13",
      "patient_age": 75,
      "patient_sex": "M",
      "date_of_death": "2023-07-29",
      "hour_of_death": 16,
      "home_visit_same_day": 0,
      "place_of_death": "care_home",
      "cause_category": "respiratory",
      "doctor_practice_type": "urban"
    },
    {
      "patient_id": "P02911",
      "doctor_id": "D14",
      "patient_age": 50,
      "patient_sex": "F",
      "date_of_death": "2022-08-18",
      "hour_of_death": 10,
      "home_visit_same_day": 0,
      "place_of_death": "hospital",
      "cause_category": "respiratory",
      "doctor_practice_type": "urban"
    },
    {
      "patient_id": "P02929",
      "doctor_id": "D14",
      "patient_age": 82,
      "patient_sex": "M",
      "date_of_death": "2023-03-22",
      "hour_of_death": 15,
      "home_visit_same_day": 1,
      "place_of_death": "care_home",
      "cause_category": "other",
      "doctor_practice_type": "urban"
    },
    {
      "patient_id": "P02940",
      "doctor_id": "D14",
      "patient_age": 72,
      "patient_sex": "M",
      "date_of_death": "2022-02-18",
      "hour_of_death": 14,
      "home_visit_same_day": 0,
      "place_of_death": "home",
      "cause_category": "respiratory",
      "doctor_practice_type": "urban"
    },
    {
      "patient_id": "P02949",
      "doctor_id": "D14",
      "patient_age": 94,
      "patient_sex": "F",
      "date_of_death": "2022-03-02",
      "hour_of_death": 16,
      "home_visit_same_day": 1,
      "place_of_death": "hospital",
      "cause_category": "cancer",
      "doctor_practice_type": "urban"
    },
    {
      "patient_id": "P03022",
      "doctor_id": "D14",
      "patient_age": 68,
      "patient_sex": "M",
      "date_of_death": "2022-10-05",
      "hour_of_death": 5,
      "home_visit_same_day": 0,
      "place_of_death": "hospital",
      "cause_category": "other",
      "doctor_practice_type": "urban"
    },
    {
      "patient_id": "P03033",
      "doctor_id": "D14",
      "patient_age": 72,
      "patient_sex": "F",
      "date_of_death": "2023-06-12",
      "hour_of_death": 17,
      "home_visit_same_day": 0,
      "place_of_death": "hospital",
      "cause_category": "other",
      "doctor_practice_type": "urban"
    },
    {
      "patient_id": "P03057",
      "doctor_id": "D14",
      "patient_age": 89,
      "patient_sex": "F",
      "date_of_death": "2022-07-21",
      "hour_of_death": 0,
      "home_visit_same_day": 0,
      "place_of_death": "hospital",
      "cause_category": "cardiovascular",
      "doctor_practice_type": "urban"
    },
    {
      "patient_id": "P03058",
      "doctor_id": "D14",
      "patient_age": 98,
      "patient_sex": "F",
      "date_of_death": "2023-11-01",
      "hour_of_death": 13,
      "home_visit_same_day": 0,
      "place_of_death": "home",
      "cause_category": "cardiovascular",
      "doctor_practice_type": "urban"
    },
    {
      "patient_id": "P03074",
      "doctor_id": "D14",
      "patient_age": 60,
      "patient_sex": "M",
      "date_of_death": "2022-01-24",
      "hour_of_death": 10,
      "home_visit_same_day": 0,
      "place_of_death": "home",
      "cause_category": "frailty",
      "doctor_practice_type": "urban"
    },
    {
      "patient_id": "P03079",
      "doctor_id": "D14",
      "patient_age": 69,
      "patient_sex": "F",
      "date_of_death": "2022-09-30",
      "hour_of_death": 8,
      "home_visit_same_day": 1,
      "place_of_death": "hospital",
      "cause_category": "frailty",
      "doctor_practice_type": "urban"
    },
    {
      "patient_id": "P03124",
      "doctor_id": "D14",
      "patient_age": 81,
      "patient_sex": "M",
      "date_of_death": "2022-05-01",
      "hour_of_death": 23,
      "home_visit_same_day": 0,
      "place_of_death": "home",
      "cause_category": "cardiovascular",
      "doctor_practice_type": "urban"
    },
    {
      "patient_id": "P03140",
      "doctor_id": "D15",
      "patient_age": 77,
      "patient_sex": "M",
      "date_of_death": "2023-04-18",
      "hour_of_death": 0,
      "home_visit_same_day": 0,
      "place_of_death": "home",
      "cause_category": "cardiovascular",
      "doctor_practice_type": "rural"
    },
    {
      "patient_id": "P03160",
      "doctor_id": "D15",
      "patient_age": 78,
      "patient_sex": "M",
      "date_of_death": "2022-08-18",
      "hour_of_death": 13,
      "home_visit_same_day": 0,
      "place_of_death": "hospital",
      "cause_category": "cardiovascular",
      "doctor_practice_type": "rural"
    },
    {
      "patient_id": "P03171",
      "doctor_id": "D15",
      "patient_age": 83,
      "patient_sex": "M",
      "date_of_death": "2022-03-13",
      "hour_of_death": 11,
      "home_visit_same_day": 0,
      "place_of_death": "hospital",
      "cause_category": "respiratory",
      "doctor_practice_type": "rural"
    },
    {
      "patient_id": "P03234",
      "doctor_id": "D15",
      "patient_age": 72,
      "patient_sex": "M",
      "date_of_death": "2022-10-31",
      "hour_of_death": 6,
      "home_visit_same_day": 0,
      "place_of_death": "hospital",
      "cause_category": "frailty",
      "doctor_practice_type": "rural"
    },
    {
      "patient_id": "P03253",
      "doctor_id": "D15",
      "patient_age": 74,
      "patient_sex": "F",
      "date_of_death": "2022-09-08",
      "hour_of_death": 6,
      "home_visit_same_day": 0,
      "place_of_death": "hospital",
      "cause_category": "other",
      "doctor_practice_type": "rural"
    },
    {
      "patient_id": "P03266",
      "doctor_id": "D15",
      "patient_age": 83,
      "patient_sex": "F",
      "date_of_death": "2023-04-22",
      "hour_of_death": 9,
      "home_visit_same_day": 1,
      "place_of_death": "home",
      "cause_category": "cardiovascular",
      "doctor_practice_type": "rural"
    },
    {
      "patient_id": "P03289",
      "doctor_id": "D15",
      "patient_age": 65,
      "patient_sex": "M",
      "date_of_death": "2022-05-22",
      "hour_of_death": 7,
      "home_visit_same_day": 0,
      "place_of_death": "home",
      "cause_category": "frailty",
      "doctor_practice_type": "rural"
    },
    {
      "patient_id": "P03346",
      "doctor_id": "D15",
      "patient_age": 62,
      "patient_sex": "F",
      "date_of_death": "2023-07-07",
      "hour_of_death": 16,
      "home_visit_same_day": 0,
      "place_of_death": "home",
      "cause_category": "cardiovascular",
      "doctor_practice_type": "rural"
    },
    {
      "patient_id": "P03354",
      "doctor_id": "D16",
      "patient_age": 87,
      "patient_sex": "F",
      "date_of_death": "2023-07-31",
      "hour_of_death": 12,
      "home_visit_same_day": 1,
      "place_of_death": "home",
      "cause_category": "cancer",
      "doctor_practice_type": "urban"
    },
    {
      "patient_id": "P03361",
      "doctor_id": "D16",
      "patient_age": 95,
      "patient_sex": "M",
      "date_of_death": "2022-01-15",
      "hour_of_death": 15,
      "home_visit_same_day": 1,
      "place_of_death": "hospital",
      "cause_category": "cardiovascular",
      "doctor_practice_type": "urban"
    },
    {
      "patient_id": "P03381",
      "doctor_id": "D16",
      "patient_age": 84,
      "patient_sex": "F",
      "date_of_death": "2022-01-26",
      "hour_of_death": 19,
      "home_visit_same_day": 0,
      "place_of_death": "home",
      "cause_category": "cardiovascular",
      "doctor_practice_type": "urban"
    },
    {
      "patient_id": "P03393",
      "doctor_id": "D16",
      "patient_age": 61,
      "patient_sex": "F",
      "date_of_death": "2023-11-10",
      "hour_of_death": 6,
      "home_visit_same_day": 0,
      "place_of_death": "care_home",
      "cause_category": "respiratory",
      "doctor_practice_type": "urban"
    },
    {
      "patient_id": "P03459",
      "doctor_id": "D16",
      "patient_age": 64,
      "patient_sex": "M",
      "date_of_death": "2023-03-08",
      "hour_of_death": 16,
      "home_visit_same_day": 0,
      "place_of_death": "care_home",
      "cause_category": "frailty",
      "doctor_practice_type": "urban"
    },
    {
      "patient_id": "P03460",
      "doctor_id": "D16",
      "patient_age": 81,
      "patient_sex": "F",
      "date_of_death": "2022-11-01",
      "hour_of_death": 3,
      "home_visit_same_day": 0,
      "place_of_death": "care_home",
      "cause_category": "cardiovascular",
      "doctor_practice_type": "urban"
    },
    {
      "patient_id": "P03473",
      "doctor_id": "D16",
      "patient_age": 66,
      "patient_sex": "M",
      "date_of_death": "2022-04-06",
      "hour_of_death": 2,
      "home_visit_same_day": 1,
      "place_of_death": "care_home",
      "cause_category": "frailty",
      "doctor_practice_type": "urban"
    },
    {
      "patient_id": "P03476",
      "doctor_id": "D16",
      "patient_age": 70,
      "patient_sex": "M",
      "date_of_death": "2023-09-02",
      "hour_of_death": 2,
      "home_visit_same_day": 0,
      "place_of_death": "home",
      "cause_category": "respiratory",
      "doctor_practice_type": "urban"
    },
    {
      "patient_id": "P03510",
      "doctor_id": "D16",
      "patient_age": 71,
      "patient_sex": "M",
      "date_of_death": "2023-07-03",
      "hour_of_death": 20,
      "home_visit_same_day": 0,
      "place_of_death": "care_home",
      "cause_category": "frailty",
      "doctor_practice_type": "urban"
    },
    {
      "patient_id": "P03538",
      "doctor_id": "D16",
      "patient_age": 86,
      "patient_sex": "M",
      "date_of_death": "2023-08-16",
      "hour_of_death": 15,
      "home_visit_same_day": 1,
      "place_of_death": "home",
      "cause_category": "cancer",
      "doctor_practice_type": "urban"
    },
    {
      "patient_id": "P03540",
      "doctor_id": "D16",
      "patient_age": 75,
      "patient_sex": "F",
      "date_of_death": "2023-06-09",
      "hour_of_death": 10,
      "home_visit_same_day": 1,
      "place_of_death": "home",
      "cause_category": "cardiovascular",
      "doctor_practice_type": "urban"
    },
    {
      "patient_id": "P03560",
      "doctor_id": "D16",
      "patient_age": 74,
      "patient_sex": "F",
      "date_of_death": "2023-09-25",
      "hour_of_death": 7,
      "home_visit_same_day": 0,
      "place_of_death": "home",
      "cause_category": "frailty",
      "doctor_practice_type": "urban"
    },
    {
      "patient_id": "P03564",
      "doctor_id": "D16",
      "patient_age": 75,
      "patient_sex": "M",
      "date_of_death": "2023-04-03",
      "hour_of_death": 12,
      "home_visit_same_day": 1,
      "place_of_death": "care_home",
      "cause_category": "frailty",
      "doctor_practice_type": "urban"
    },
    {
      "patient_id": "P03596",
      "doctor_id": "D17",
      "patient_age": 80,
      "patient_sex": "M",
      "date_of_death": "2022-12-11",
      "hour_of_death": 2,
      "home_visit_same_day": 0,
      "place_of_death": "hospital",
      "cause_category": "respiratory",
      "doctor_practice_type": "suburban"
    },
    {
      "patient_id": "P03621",
      "doctor_id": "D17",
      "patient_age": 66,
      "patient_sex": "F",
      "date_of_death": "2022-05-18",
      "hour_of_death": 18,
      "home_visit_same_day": 0,
      "place_of_death": "hospital",
      "cause_category": "cardiovascular",
      "doctor_practice_type": "suburban"
    },
    {
      "patient_id": "P03643",
      "doctor_id": "D17",
      "patient_age": 65,
      "patient_sex": "F",
      "date_of_death": "2023-11-09",
      "hour_of_death": 3,
      "home_visit_same_day": 1,
      "place_of_death": "care_home",
      "cause_category": "other",
      "doctor_practice_type": "suburban"
    },
    {
      "patient_id": "P03659",
      "doctor_id": "D17",
      "patient_age": 72,
      "patient_sex": "F",
      "date_of_death": "2023-07-26",
      "hour_of_death": 18,
      "home_visit_same_day": 0,
      "place_of_death": "hospital",
      "cause_category": "cancer",
      "doctor_practice_type": "suburban"
    },
    {
      "patient_id": "P03688",
      "doctor_id": "D17",
      "patient_age": 84,
      "patient_sex": "F",
      "date_of_death": "2022-06-13",
      "hour_of_death": 2,
      "home_visit_same_day": 0,
      "place_of_death": "home",
      "cause_category": "other",
      "doctor_practice_type": "suburban"
    },
    {
      "patient_id": "P03691",
      "doctor_id": "D17",
      "patient_age": 84,
      "patient_sex": "F",
      "date_of_death": "2022-06-01",
      "hour_of_death": 0,
      "home_visit_same_day": 0,
      "place_of_death": "home",
      "cause_category": "cardiovascular",
      "doctor_practice_type": "suburban"
    },
    {
      "patient_id": "P03702",
      "doctor_id": "D17",
      "patient_age": 87,
      "patient_sex": "F",
      "date_of_death": "2023-01-19",
      "hour_of_death": 3,
      "home_visit_same_day": 0,
      "place_of_death": "care_home",
      "cause_category": "frailty",
      "doctor_practice_type": "suburban"
    },
    {
      "patient_id": "P03703",
      "doctor_id": "D17",
      "patient_age": 83,
      "patient_sex": "F",
      "date_of_death": "2022-07-09",
      "hour_of_death": 5,
      "home_visit_same_day": 0,
      "place_of_death": "care_home",
      "cause_category": "other",
      "doctor_practice_type": "suburban"
    },
    {
      "patient_id": "P03724",
      "doctor_id": "D17",
      "patient_age": 72,
      "patient_sex": "M",
      "date_of_death": "2023-04-17",
      "hour_of_death": 3,
      "home_visit_same_day": 0,
      "place_of_death": "home",
      "cause_category": "respiratory",
      "doctor_practice_type": "suburban"
    },
    {
      "patient_id": "P03730",
      "doctor_id": "D17",
      "patient_age": 80,
      "patient_sex": "F",
      "date_of_death": "2023-05-28",
      "hour_of_death": 5,
      "home_visit_same_day": 0,
      "place_of_death": "hospital",
      "cause_category": "respiratory",
      "doctor_practice_type": "suburban"
    },
    {
      "patient_id": "P03740",
      "doctor_id": "D17",
      "patient_age": 69,
      "patient_sex": "F",
      "date_of_death": "2023-01-31",
      "hour_of_death": 10,
      "home_visit_same_day": 1,
      "place_of_death": "hospital",
      "cause_category": "respiratory",
      "doctor_practice_type": "suburban"
    },
    {
      "patient_id": "P03767",
      "doctor_id": "D18",
      "patient_age": 83,
      "patient_sex": "M",
      "date_of_death": "2023-11-08",
      "hour_of_death": 7,
      "home_visit_same_day": 0,
      "place_of_death": "hospital",
      "cause_category": "frailty",
      "doctor_practice_type": "suburban"
    },
    {
      "patient_id": "P03772",
      "doctor_id": "D18",
      "patient_age": 73,
      "patient_sex": "F",
      "date_of_death": "2022-11-22",
      "hour_of_death": 2,
      "home_visit_same_day": 0,
      "place_of_death": "home",
      "cause_category": "frailty",
      "doctor_practice_type": "suburban"
    },
    {
      "patient_id": "P03810",
      "doctor_id": "D18",
      "patient_age": 77,
      "patient_sex": "M",
      "date_of_death": "2023-08-27",
      "hour_of_death": 6,
      "home_visit_same_day": 0,
      "place_of_death": "home",
      "cause_category": "respiratory",
      "doctor_practice_type": "suburban"
    },
    {
      "patient_id": "P03837",
      "doctor_id": "D18",
      "patient_age": 65,
      "patient_sex": "M",
      "date_of_death": "2023-08-10",
      "hour_of_death": 14,
      "home_visit_same_day": 0,
      "place_of_death": "care_home",
      "cause_category": "respiratory",
      "doctor_practice_type": "suburban"
    },
    {
      "patient_id": "P03839",
      "doctor_id": "D18",
      "patient_age": 76,
      "patient_sex": "F",
      "date_of_death": "2023-11-24",
      "hour_of_death": 17,
      "home_visit_same_day": 0,
      "place_of_death": "hospital",
      "cause_category": "frailty",
      "doctor_practice_type": "suburban"
    },
    {
      "patient_id": "P03843",
      "doctor_id": "D18",
      "patient_age": 74,
      "patient_sex": "M",
      "date_of_death": "2022-05-09",
      "hour_of_death": 7,
      "home_visit_same_day": 0,
      "place_of_death": "home",
      "cause_category": "frailty",
      "doctor_practice_type": "suburban"
    },
    {
      "patient_id": "P03849",
      "doctor_id": "D18",
      "patient_age": 70,
      "patient_sex": "F",
      "date_of_death": "2022-08-07",
      "hour_of_death": 10,
      "home_visit_same_day": 0,
      "place_of_death": "hospital",
      "cause_category": "frailty",
      "doctor_practice_type": "suburban"
    },
    {
      "patient_id": "P03877",
      "doctor_id": "D18",
      "patient_age": 88,
      "patient_sex": "F",
      "date_of_death": "2022-01-13",
      "hour_of_death": 8,
      "home_visit_same_day": 0,
      "place_of_death": "hospital",
      "cause_category": "cardiovascular",
      "doctor_practice_type": "suburban"
    },
    {
      "patient_id": "P03881",
      "doctor_id": "D18",
      "patient_age": 73,
      "patient_sex": "M",
      "date_of_death": "2022-10-19",
      "hour_of_death": 3,
      "home_visit_same_day": 0,
      "place_of_death": "home",
      "cause_category": "cancer",
      "doctor_practice_type": "suburban"
    },
    {
      "patient_id": "P03892",
      "doctor_id": "D18",
      "patient_age": 85,
      "patient_sex": "M",
      "date_of_death": "2022-12-13",
      "hour_of_death": 5,
      "home_visit_same_day": 0,
      "place_of_death": "hospital",
      "cause_category": "cardiovascular",
      "doctor_practice_type": "suburban"
    },
    {
      "patient_id": "P03895",
      "doctor_id": "D18",
      "patient_age": 79,
      "patient_sex": "F",
      "date_of_death": "2023-07-24",
      "hour_of_death": 13,
      "home_visit_same_day": 0,
      "place_of_death": "hospital",
      "cause_category": "cardiovascular",
      "doctor_practice_type": "suburban"
    },
    {
      "patient_id": "P03900",
      "doctor_id": "D18",
      "patient_age": 79,
      "patient_sex": "F",
      "date_of_death": "2022-08-08",
      "hour_of_death": 19,
      "home_visit_same_day": 1,
      "place_of_death": "home",
      "cause_category": "respiratory",
      "doctor_practice_type": "suburban"
    },
    {
      "patient_id": "P03920",
      "doctor_id": "D18",
      "patient_age": 76,
      "patient_sex": "M",
      "date_of_death": "2022-10-07",
      "hour_of_death": 12,
      "home_visit_same_day": 1,
      "place_of_death": "home",
      "cause_category": "respiratory",
      "doctor_practice_type": "suburban"
    },
    {
      "patient_id": "P03921",
      "doctor_id": "D18",
      "patient_age": 77,
      "patient_sex": "F",
      "date_of_death": "2022-09-11",
      "hour_of_death": 9,
      "home_visit_same_day": 0,
      "place_of_death": "home",
      "cause_category": "other",
      "doctor_practice_type": "suburban"
    },
    {
      "patient_id": "P03925",
      "doctor_id": "D18",
      "patient_age": 79,
      "patient_sex": "F",
      "date_of_death": "2023-11-26",
      "hour_of_death": 13,
      "home_visit_same_day": 1,
      "place_of_death": "home",
      "cause_category": "cancer",
      "doctor_practice_type": "suburban"
    },
    {
      "patient_id": "P03933",
      "doctor_id": "D18",
      "patient_age": 70,
      "patient_sex": "M",
      "date_of_death": "2022-06-18",
      "hour_of_death": 5,
      "home_visit_same_day": 0,
      "place_of_death": "hospital",
      "cause_category": "frailty",
      "doctor_practice_type": "suburban"
    },
    {
      "patient_id": "P03965",
      "doctor_id": "D18",
      "patient_age": 79,
      "patient_sex": "M",
      "date_of_death": "2023-06-08",
      "hour_of_death": 9,
      "home_visit_same_day": 0,
      "place_of_death": "hospital",
      "cause_category": "cancer",
      "doctor_practice_type": "suburban"
    },
    {
      "patient_id": "P03971",
      "doctor_id": "D18",
      "patient_age": 82,
      "patient_sex": "F",
      "date_of_death": "2022-02-23",
      "hour_of_death": 8,
      "home_visit_same_day": 0,
      "place_of_death": "hospital",
      "cause_category": "other",
      "doctor_practice_type": "suburban"
    },
    {
      "patient_id": "P03978",
      "doctor_id": "D18",
      "patient_age": 78,
      "patient_sex": "M",
      "date_of_death": "2022-02-09",
      "hour_of_death": 14,
      "home_visit_same_day": 0,
      "place_of_death": "home",
      "cause_category": "other",
      "doctor_practice_type": "suburban"
    },
    {
      "patient_id": "P04023",
      "doctor_id": "D19",
      "patient_age": 85,
      "patient_sex": "F",
      "date_of_death": "2023-06-30",
      "hour_of_death": 4,
      "home_visit_same_day": 0,
      "place_of_death": "hospital",
      "cause_category": "cancer",
      "doctor_practice_type": "suburban"
    },
    {
      "patient_id": "P04035",
      "doctor_id": "D19",
      "patient_age": 79,
      "patient_sex": "F",
      "date_of_death": "2022-05-22",
      "hour_of_death": 15,
      "home_visit_same_day": 0,
      "place_of_death": "home",
      "cause_category": "cancer",
      "doctor_practice_type": "suburban"
    },
    {
      "patient_id": "P04041",
      "doctor_id": "D19",
      "patient_age": 61,
      "patient_sex": "F",
      "date_of_death": "2023-05-19",
      "hour_of_death": 0,
      "home_visit_same_day": 0,
      "place_of_death": "care_home",
      "cause_category": "respiratory",
      "doctor_practice_type": "suburban"
    },
    {
      "patient_id": "P04050",
      "doctor_id": "D19",
      "patient_age": 80,
      "patient_sex": "F",
      "date_of_death": "2022-04-29",
      "hour_of_death": 9,
      "home_visit_same_day": 1,
      "place_of_death": "hospital",
      "cause_category": "respiratory",
      "doctor_practice_type": "suburban"
    },
    {
      "patient_id": "P04066",
      "doctor_id": "D19",
      "patient_age": 70,
      "patient_sex": "F",
      "date_of_death": "2023-02-24",
      "hour_of_death": 18,
      "home_visit_same_day": 0,
      "place_of_death": "care_home",
      "cause_category": "cardiovascular",
      "doctor_practice_type": "suburban"
    },
    {
      "patient_id": "P04174",
      "doctor_id": "D19",
      "patient_age": 92,
      "patient_sex": "M",
      "date_of_death": "2023-04-11",
      "hour_of_death": 6,
      "home_visit_same_day": 0,
      "place_of_death": "hospital",
      "cause_category": "cancer",
      "doctor_practice_type": "suburban"
    },
    {
      "patient_id": "P04176",
      "doctor_id": "D19",
      "patient_age": 78,
      "patient_sex": "F",
      "date_of_death": "2023-06-12",
      "hour_of_death": 3,
      "home_visit_same_day": 0,
      "place_of_death": "home",
      "cause_category": "frailty",
      "doctor_practice_type": "suburban"
    },
    {
      "patient_id": "P04192",
      "doctor_id": "D19",
      "patient_age": 73,
      "patient_sex": "M",
      "date_of_death": "2022-12-12",
      "hour_of_death": 1,
      "home_visit_same_day": 0,
      "place_of_death": "home",
      "cause_category": "cardiovascular",
      "doctor_practice_type": "suburban"
    },
    {
      "patient_id": "P04213",
      "doctor_id": "D20",
      "patient_age": 84,
      "patient_sex": "M",
      "date_of_death": "2023-10-15",
      "hour_of_death": 6,
      "home_visit_same_day": 1,
      "place_of_death": "care_home",
      "cause_category": "cancer",
      "doctor_practice_type": "rural"
    },
    {
      "patient_id": "P04225",
      "doctor_id": "D20",
      "patient_age": 91,
      "patient_sex": "F",
      "date_of_death": "2023-02-28",
      "hour_of_death": 22,
      "home_visit_same_day": 0,
      "place_of_death": "home",
      "cause_category": "respiratory",
      "doctor_practice_type": "rural"
    },
    {
      "patient_id": "P04239",
      "doctor_id": "D20",
      "patient_age": 79,
      "patient_sex": "M",
      "date_of_death": "2023-10-15",
      "hour_of_death": 18,
      "home_visit_same_day": 0,
      "place_of_death": "hospital",
      "cause_category": "other",
      "doctor_practice_type": "rural"
    },
    {
      "patient_id": "P04259",
      "doctor_id": "D20",
      "patient_age": 68,
      "patient_sex": "M",
      "date_of_death": "2023-01-24",
      "hour_of_death": 7,
      "home_visit_same_day": 0,
      "place_of_death": "care_home",
      "cause_category": "respiratory",
      "doctor_practice_type": "rural"
    },
    {
      "patient_id": "P04287",
      "doctor_id": "D20",
      "patient_age": 83,
      "patient_sex": "M",
      "date_of_death": "2023-12-27",
      "hour_of_death": 14,
      "home_visit_same_day": 0,
      "place_of_death": "hospital",
      "cause_category": "cancer",
      "doctor_practice_type": "rural"
    },
    {
      "patient_id": "P04304",
      "doctor_id": "D20",
      "patient_age": 81,
      "patient_sex": "F",
      "date_of_death": "2022-04-11",
      "hour_of_death": 7,
      "home_visit_same_day": 0,
      "place_of_death": "home",
      "cause_category": "cancer",
      "doctor_practice_type": "rural"
    },
    {
      "patient_id": "P04313",
      "doctor_id": "D20",
      "patient_age": 91,
      "patient_sex": "F",
      "date_of_death": "2023-07-06",
      "hour_of_death": 16,
      "home_visit_same_day": 1,
      "place_of_death": "care_home",
      "cause_category": "cancer",
      "doctor_practice_type": "rural"
    },
    {
      "patient_id": "P04323",
      "doctor_id": "D20",
      "patient_age": 81,
      "patient_sex": "F",
      "date_of_death": "2022-01-28",
      "hour_of_death": 2,
      "home_visit_same_day": 0,
      "place_of_death": "care_home",
      "cause_category": "other",
      "doctor_practice_type": "rural"
    },
    {
      "patient_id": "P04396",
      "doctor_id": "D20",
      "patient_age": 88,
      "patient_sex": "M",
      "date_of_death": "2022-10-26",
      "hour_of_death": 9,
      "home_visit_same_day": 1,
      "place_of_death": "hospital",
      "cause_category": "frailty",
      "doctor_practice_type": "rural"
    }
  ]
};